# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true
gems: [jekyll-paginate,jekyll-gist]
# Setup
title:            Sukesh
tagline:          'Software engineer'
description:      'Software engineer, machine learning enthusiast.'
url:              http://sukesh1989.github.io/blog
baseurl:          /blog/

author:
  name:           'Sukesh Salian'
  url:            https://twitter.com/fatindiancoder

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sukesh1989
